### ISSUE TITLE
new error TypeError('must start with number, buffer, array or string')

### ISSUE THREAD

**Issue by prosenjit-manna** [konitter/gulp-combine-media-queries#24]
wp-content/themes/projectname/scss/main.css found.
buffer.js:167
  throw new TypeError('must start with number, buffer, array or string');
  ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:167:9)
    at new Buffer (buffer.js:58:10)
    at Transform.transform [as _transform](/Users/username/dev/projectname/node_modules/gulp-combine-media-queries/index.js:152:21)
    at Transform._read (/Users/username/dev/projectname/node_modules/gulp-combine-media-queries/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/username/dev/projectname/node_modules/gulp-combine-media-queries/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/username/dev/projectname/node_modules/gulp-combine-media-queries/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/username/dev/projectname/node_modules/gulp-combine-media-queries/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users/username/dev/projectname/node_modules/gulp-combine-media-queries/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at DestroyableTransform.ondata (/Users/username/dev/projectname/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:583:20)
    at emitOne (events.js:77:13)
Segmentation fault: 11

**Comment by YozhEzhi** [comment]
+1
@prosenjit-itobuz  But as you can see last commit was a year ago.

**Comment by prosenjit-manna** [comment]
I didn't notice that. :+1:  

gulp-group-css-media-queries fix my problem

**Comment by evanre** [comment]
@prosenjit-itobuz thanks a lot for good replacement. :+1:

**Comment by GuiAlmeida** [comment]
@prosenjit-itobuz  thanks!!!!!

**Comment by iljapanic** [comment]
@prosenjit-itobuz Thank you good sir!

**Comment by felipefialho** [comment]
Thanks @prosenjit-itobuz ;)
