### ISSUE TITLE
throw new TypeError(kFromErrorMsg);

### ISSUE THREAD

**Issue by rustamwin** [konitter/gulp-combine-media-queries#28]
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at new Buffer (buffer.js:158:17)
    at Transform.transform [as _transform] (/var/www/xabar-html/node_modules/gulp-combine-media-queries/index.js:152:21)
    at Transform._read (/var/www/xabar-html/node_modules/gulp-combine-media-queries/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/var/www/xabar-html/node_modules/gulp-combine-media-queries/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/var/www/xabar-html/node_modules/gulp-combine-media-queries/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/var/www/xabar-html/node_modules/gulp-combine-media-queries/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/var/www/xabar-html/node_modules/gulp-combine-media-queries/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Readable.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)

**Comment by acenkus** [comment]
Same error to me

**Comment by tiagocastro070** [comment]
Any solution?

**Comment by rustamwin** [comment]
@tiagocastro070 rollback node version to 4
